## Sample docker-compose file to run jellenberger/jupyter-base.

version: '3'

services:
  jupyter:
    image: jellenberger/jupyter-base
    volumes:
      - ${PWD}:/home/appuser/work # mount current local directory at container ~/work dir
      - ${HOME}/data:/home/appuser/data # mount local ~/data repo at container ~/data dir
    ports:
      - 8888:8888
    container_name: jupyter_base
