## Sample docker-compose file to run jellenberger/jupyter-base.

version: '3'

services:
  jupyter:
    image: jupyter/scipy-notebook
    volumes:
      - ./work:/home/jovyan/work
      - ./data:/home/jovyan/data
    ports:
      - 8888:8888

      #   db:
#     image: postgres:11-alpine
#     environment:
#       - POSTGRES_DB=${POSTGRES_USER}
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

#     volumes:
#       - postgres_data:/var/lib/postgresql/data/

# volumes:
#   postgres_data: