## Sample docker-compose file to run jellenberger/jupyter-base.

version: '3'

services:
  jupyter:
    image: jellenberger/jupyter-base
    volumes:
      - ./notebooks:/home/appuser/notebooks
      - ./data:/home/appuser/data
    ports:
      - 8888:8888
