## Sample docker-compose file to run jellenberger/fastai-base

version: '3'

services:
  jupyter:
    image: jellenberger/fastai-base
    shm_size: '2gb'  # see https://github.com/pytorch/pytorch/issues/2244; increase if necessary
    volumes:
      - ${PWD}:/home/appuser/work # mount current local directory at container ~/work dir
      - ${HOME}/data:/home/appuser/data # mount local ~/data repo at container ~/data dir
    ports:
      - 8888:8888
    container_name: fastai_base
